CC = javac
CC2 = jar
ARQS = controller/*.java view/*.java model/*.java dao/*.java
ARQS2 = MANIFEST.txt controller/*.class view/*.class model/*.class dao/*.class

all:
	$(CC) $(ARQS)
	$(CC2) cfm QuebraDeBarreira.jar $(ARQS2)